// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Step",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Step",
            targets: ["AppModule"],
            bundleIdentifier: "me.chandramdutta.Step",
            teamIdentifier: "DR99P625RR",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly),
                .fileAccess(.pictureFolder, mode: .readOnly),
                .fileAccess(.musicFolder, mode: .readOnly),
                .fileAccess(.moviesFolder, mode: .readOnly)
            ],
            appCategory: .music
        )
    ],
    dependencies: [
        .package(url: "https://github.com/dmrschmidt/DSWaveformImage.git", "14.0.0"..<"15.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DSWaveformImage", package: "dswaveformimage"),
                .product(name: "DSWaveformImageViews", package: "dswaveformimage")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)